/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  customerName?: string;
  customerEmail?: string;
  clerkUserId?: string;
  products?: Array<{
    product?: ProductReference;
    quantity?: number;
    price?: number;
    _type: "ordersData";
    _key: string;
  }>;
  totalPrice?: number;
  status?: "pending" | "paid" | "processing" | "shipped" | "delivered" | "cancelled";
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  stripePaymentIntent?: string;
  orderDate?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  invoice?: {
    invoiceId?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "Category";
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  price?: number;
  discount?: number;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  stock?: number;
  brand?: BrandReference;
  status?: "new" | "hot" | "sale";
  variant?: "gadget" | "appliances" | "refrigerators" | "others";
  isFeatured?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  string?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type BlogCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogCategory";
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories?: Array<{
    _key: string;
  } & BlogCategoryReference>;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type BlogCategory = {
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Address = {
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  emailAddress?: string;
  phone?: string;
  address?: string;
  streetAddress?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  country?: string;
  countryCode?: string;
  stateCode?: string;
  subArea?: string;
  addressType?: "home" | "office" | "other";
  default?: boolean;
  createdAt?: string;
};

export type Category = {
  _id: string;
  _type: "Category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ProductReference | Order | SanityImageAssetReference | CategoryReference | BrandReference | Product | SanityImageCrop | SanityImageHotspot | Slug | Brand | AuthorReference | BlogCategoryReference | Blog | BlockContent | BlogCategory | Author | Address | Category | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/queries/index.ts
// Variable: BRANDS_QUERY
// Query: *[_type == "brand"] | order(title asc){    _id,    string,    slug,  image{     _type,    asset,  }}
export type BRANDS_QUERYResult = Array<{
  _id: string;
  string: string | null;
  slug: Slug | null;
  image: {
    _type: "image";
    asset: SanityImageAssetReference | null;
  } | null;
}>;
// Variable: BLOGS_QUERY
// Query: *[_type == "blog" && isLatest == true] | order(title asc){  ...,  blogcategories[]->{    title  }}
export type BLOGS_QUERYResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest: true;
  body?: BlockContent;
}>;
// Variable: HOTDEALS_QUERY
// Query: *[_type == 'product' && status == "hot"] | order(name asc){  ...,  "categories":categories[]->{    title  }}
export type HOTDEALS_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  price?: number;
  discount?: number;
  categories: Array<{
    title: string | null;
  }> | null;
  stock?: number;
  brand?: BrandReference;
  status: "hot";
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
}>;
// Variable: SINGLEPRODUCT_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{    ...,    brand->{    ...,    }    }
export type SINGLEPRODUCT_QUERYResult = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  price?: number;
  discount?: number;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  stock?: number;
  brand: {
    _id: string;
    _type: "brand";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    string?: string;
    slug?: Slug;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  } | null;
  status?: "hot" | "new" | "sale";
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
} | null;
// Variable: RANDOMDATA_QUERY
// Query: *[_type == "product"]{        ...,        "categories":categories[]->{        _id,        title,        }        }
export type RANDOMDATA_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  price?: number;
  discount?: number;
  categories: Array<{
    _id: string;
    title: string | null;
  }> | null;
  stock?: number;
  brand?: BrandReference;
  status?: "hot" | "new" | "sale";
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
}>;
// Variable: ALLPRODUCTS_QUERY
// Query: *[_type == "product"]
export type ALLPRODUCTS_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  price?: number;
  discount?: number;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  stock?: number;
  brand?: BrandReference;
  status?: "hot" | "new" | "sale";
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
}>;
// Variable: USERADDRESS_QUERY
// Query: *[_type == "address"] | order(_createdAt asc)
export type USERADDRESS_QUERYResult = Array<{
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  emailAddress?: string;
  phone?: string;
  address?: string;
  streetAddress?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  country?: string;
  countryCode?: string;
  stateCode?: string;
  subArea?: string;
  addressType?: "home" | "office" | "other";
  default?: boolean;
  createdAt?: string;
}>;
// Variable: USERORDERS_QUERY
// Query: *[_type == "order" && clerkUserId == $userId] | order(orderDate desc) {    ...,     products[]{      ...,      product->{        ...      }    }  }
export type USERORDERS_QUERYResult = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  customerName?: string;
  customerEmail?: string;
  clerkUserId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      description?: string;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      price?: number;
      discount?: number;
      categories?: Array<{
        _key: string;
      } & CategoryReference>;
      stock?: number;
      brand?: BrandReference;
      status?: "hot" | "new" | "sale";
      variant?: "appliances" | "gadget" | "others" | "refrigerators";
      isFeatured?: boolean;
      averageRating?: number;
      totalReviews?: number;
      ratingDistribution?: {
        fiveStars?: number;
        fourStars?: number;
        threeStars?: number;
        twoStars?: number;
        oneStar?: number;
      };
    } | null;
    quantity?: number;
    price?: number;
    _type: "ordersData";
    _key: string;
  }> | null;
  totalPrice?: number;
  status?: "cancelled" | "delivered" | "paid" | "pending" | "processing" | "shipped";
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  stripePaymentIntent?: string;
  orderDate?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  invoice?: {
    invoiceId?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
}>;
// Variable: DELETEUSERORDERS_QUERY
// Query: *[_type == "order" && orderNumber == $orderNumber]
export type DELETEUSERORDERS_QUERYResult = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  customerName?: string;
  customerEmail?: string;
  clerkUserId?: string;
  products?: Array<{
    product?: ProductReference;
    quantity?: number;
    price?: number;
    _type: "ordersData";
    _key: string;
  }>;
  totalPrice?: number;
  status?: "cancelled" | "delivered" | "paid" | "pending" | "processing" | "shipped";
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  stripePaymentIntent?: string;
  orderDate?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  invoice?: {
    invoiceId?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
}>;
// Variable: GETALLBLOGS_QUERY
// Query: *[_type == "blog"] | order(publishedAt desc){  ...,  blogcategories[]->{    title  }  }
export type GETALLBLOGS_QUERYResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
}>;
// Variable: GETSINGLEBLOG_QUERY
// Query: *[_type == "blog" && slug.current == $slug]{  ...,  author->{  name,image},  blogcategories[]->{  title,  "slug":slug.current  }  }
export type GETSINGLEBLOG_QUERYResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
}>;
// Variable: GETBLOGCATEGORIES_QUERY
// Query: *[_type == "blog"]{    blogcategories[]->{    ...    }  }
export type GETBLOGCATEGORIES_QUERYResult = Array<{
  blogcategories: Array<{
    _id: string;
    _type: "blogCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    description?: string;
  }> | null;
}>;
// Variable: GETOTHERBLOGS_QUERY
// Query: *[_type == "blog" && defined(slug) && slug.current != $slug] | order(publishedAt desc)[0...$quantity]{    ...,    author->{      name,      image    },    blogcategories[]->{      title,      "slug": slug.current    }  }
export type GETOTHERBLOGS_QUERYResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"brand\"] | order(title asc){\n    _id,\n    string,\n    slug,\n  image{\n     _type,\n    asset,\n  }\n}": BRANDS_QUERYResult;
    "*[_type == \"blog\" && isLatest == true] | order(title asc){\n  ...,\n  blogcategories[]->{\n    title\n  }\n}": BLOGS_QUERYResult;
    "\n    *[_type == 'product' && status == \"hot\"] | order(name asc){\n  ...,\n  \"categories\":categories[]->{\n    title\n  }\n}": HOTDEALS_QUERYResult;
    "*[_type == \"product\" && slug.current == $slug][0]{\n    ...,\n    brand->{\n    ...,\n    }\n    }": SINGLEPRODUCT_QUERYResult;
    "*[_type == \"product\"]{\n        ...,\n        \"categories\":categories[]->{\n        _id,\n        title,\n        }\n        }": RANDOMDATA_QUERYResult;
    "*[_type == \"product\"]": ALLPRODUCTS_QUERYResult;
    "*[_type == \"address\"] | order(_createdAt asc)": USERADDRESS_QUERYResult;
    "\n  *[_type == \"order\" && clerkUserId == $userId] | order(orderDate desc) {\n    ..., \n    products[]{\n      ...,\n      product->{\n        ...\n      }\n    }\n  }\n": USERORDERS_QUERYResult;
    "\n  *[_type == \"order\" && orderNumber == $orderNumber]\n": DELETEUSERORDERS_QUERYResult;
    "\n  *[_type == \"blog\"] | order(publishedAt desc){\n  ...,\n  blogcategories[]->{\n    title\n  }\n  }\n  ": GETALLBLOGS_QUERYResult;
    "\n  *[_type == \"blog\" && slug.current == $slug]{\n  ...,\n  author->{\n  name,image},\n  blogcategories[]->{\n  title,\n  \"slug\":slug.current\n  }\n  }\n  ": GETSINGLEBLOG_QUERYResult;
    "*[_type == \"blog\"]{\n    blogcategories[]->{\n    ...\n    }\n  }": GETBLOGCATEGORIES_QUERYResult;
    "\n  *[_type == \"blog\" && defined(slug) && slug.current != $slug] | order(publishedAt desc)[0...$quantity]{\n    ...,\n    author->{\n      name,\n      image\n    },\n    blogcategories[]->{\n      title,\n      \"slug\": slug.current\n    }\n  }\n": GETOTHERBLOGS_QUERYResult;
  }
}
